### PR TITLE
replace KAE with `kotlin-parcelize` and update dependencies

### LINKED ISSUE #428: "Test events were not received" on `ConfigUtilsTest`
## Expected Behavior
Unit test running and passed

## Actual Behavior
Unit test can not be run due to "Test events were not received"
image

## Steps to Reproduce the Problem

  1. Run `ConfigUtilsTest`

## Specifications

  - Image Picker Version: 3
  - Android OS: none, it is unit test
  - Phone: none, it is unit test

### PR DESCRIPTION
**Pull request by wiryadev**
With Kotlin 1.8 is around the corner, KAE will be gone soon enough. So i think it is the right time to remove that. Comple changelog of this PR:
- replace KAE plugin with `kotlin-parcelize`
- upgrade AGP version to 7.3.1
- update Glide to 4.14.2 and other dependencies
- rename rule variable naming for consistency
- fix #428 

All unit test and UI test is running and passed
image

image

### CODE REVIEW

**Comment by esafirm** [comment]
Thanks for the PR @wiryadev this is superb!
Can you resolve the conflicts first? Will approve and run the Ci after that. Thanks once again

**Comment by wiryadev** [comment]
Should be fine now ;D @esafirm

File: imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerConfig.kt [hunk 1]
```diff
@@ -30,6 +31,7 @@ class ImagePickerConfig(
     var showDoneButtonAlways: Boolean = false
 ) : BaseConfig(), Parcelable {
 
+    @IgnoredOnParcel
```
Comment (esafirm) [inline imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerConfig.kt:34]: Question: is `@Transient` still included in parcelize's pacel?

**Comment by esafirm** [comment]
The test looks good, this PR is really needed by the library, thanks again @wiryadev 👍

File: imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerConfig.kt (hunk 1 above)
Comment (wiryadev) [reply imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerConfig.kt:34]: Im not sure about `@Transient`, based on this [SO answer](https://stackoverflow.com/a/54434904), it has no effect on parcelable project. What im sure is property that is not in primary constructor will be ignored since it is mentioned in [official docs](https://developer.android.com/kotlin/parcelize) of kottlin parcelize.
